"""added added_by field

Revision ID: 843521e55752
Revises: 
Create Date: 2023-12-26 12:10:40.058329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843521e55752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
